name : Vitest Unit Test
on : [push]

jobs : 
  vitest : 
    runs-on : ubuntu-latest
    steps : 
      - name : ✓ Checkout
        uses : actions/checkout@v3
      - name : 🌱 Setup node
        uses : actions/setup-node@v3
        with : 
          node-version: 14
      - uses: borales/actions-yarn@v3.0.0
         with:
          cmd: install
      - name: ⚡ Run vitest
        run: yarn test:run --coverage